# -*- coding: utf-8 -*-
"""Hamming_distance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NumqkvA3sPYj4ucapQg5Dh6OLu_Hbye7

Write a python function for calculating the hamming distance between your slack username (e.g josoga) and twitter/X (joseph) handle (synthesize one if you don’t have one). Feel free to pad it with extra words if they are not of the same length.
"""

def hamming_dist(sla_name,twi_name):  #Function to calculate the hamming distance, accepting strings as input
  sla_list=list(sla_name)             #Converting the string into array
  twi_list=list(twi_name)             #Converting the string into array
  missmatch=0
  if len(sla_list)==len(twi_list):
    print("The strings are of same size")
    for i in range(len(sla_list)):
      if sla_list[i]!=twi_list[i]:    #comparing the list elementwise
        missmatch+=1
  else:
    print("The strings are of different size")
    print("Padding and making the strings to same size")
    max_length=max(len(sla_list),len(twi_list))
    sla_list+=["X"]*(max_length-len(sla_list))  #Making the lists of same size by padding letters
    twi_list+=["X"]*(max_length-len(twi_list))
    hamming_dist(sla_list,twi_list)

  return missmatch

sla_uname="vishnu shiri"
twi_uname="vishnu shiri"
print(f"The Hamming ditance between my slack user name and twitter user name is {hamming_dist(sla_uname,twi_uname)}")